services:
  - type: web
    name: frontend
    runtime: docker
    rootDir: ./client
    envVars:
      - key: REACT_APP_API_URL
        value: 3000
    healthCheckPath: /

  - type: web
    name: backend
    runtime: docker
    rootDir: ./server
    envVars:
      - key: PORT
        value: 4444
      - key: DATABASE_URL
        fromDatabase:
          name: POSTGRES_DB
          property: connectionString
      - key: JWT_SECRET
        value: "your_secret"
      - key: SENDER_EMAIL
        value: "testing@test.con"
      - key: PASSWORD
        value: "your_password"
    healthCheckPath: /

databases:
  - name: elephant

  - name: private database
    databaseName: private
